doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            AppClient:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Client/Entity'
                prefix: 'App\Client\Entity'
                alias: AppClient
            AppRegistration:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Client/Registration/Entity'
                prefix: 'App\Client\Registration\Entity'
                alias: AppRegistration
            AppSubscription:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Client/Subscription/Entity'
                prefix: 'App\Client\Subscription\Entity'
                alias: AppSubscription
        