controllers:
    resource: ../../src/Controller/
    type: annotation
client_controllers:
    resource: ../../src/Client/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
